version: '3'

services:
  nginx:
    build:
      context: ./requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - ./data/wordpress:/var/www/html
    networks:
      - inception_network
    depends_on:
      - wordpress
    restart: always

  wordpress:
    build:
      context: ./requirements/wordpress
    container_name: wordpress
    volumes:
      - ./data/wordpress:/var/www/html
    networks:
      - inception_network
    depends_on:
      - mariadb
    env_file:
      - .env
    restart: always

  mariadb:
    build:
      context: ./requirements/mariadb
    container_name: mariadb
    volumes:
      - ./data/mariadb:/var/lib/mysql
    networks:
      - inception_network
    env_file:
      - .env
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  inception_network:
    driver: bridge
