name: inception

services:
  nginx:
    image: nginx
    container_name: nginx
    build:
      context: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - vol_nginx_wordpress:/var/www/html
    networks:
      - inception_network
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
    depends_on:
      - wordpress
    restart: on-failure
  healthcheck:
    test: ["CMD", "curl", "--fail", "https://localhost/wp-admin/" "--insecure" || "exit 1"]
    interval: 10s
    timeout: 5s
    retries: 3

  wordpress:
    image: wordpress
    container_name: wordpress
    build:
      context: ./requirements/wordpress
    volumes:
      - vol_nginx_wordpress:/var/www/html
    networks:
      - inception_network
    depends_on:
      - mariadb
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - WP_TITLE=${WP_TITLE}
      - WP_ADMIN_USER=${WP_ADMIN_USER}
      - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
      - WP_USER=${WP_USER}
      - WP_USER_EMAIL=${WP_USER_EMAIL}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
    secrets:
      - db_password
      - db_root_password
      - wp_admin_password
      - wp_user_password
    restart: on-failure
  healthcheck:
    test: ["CMD", "php", "-f", "/var/www/html/wp-includes/version.php"]
    interval: 10s
    timeout: 5s
    retries: 3

  mariadb:
    image: mariadb
    container_name: mariadb
    build:
      context: ./requirements/mariadb
    secrets:
      - db_password
      - db_root_password
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
    volumes:
      - vol_mariadb:/var/lib/mysql
    networks:
      - inception_network
    restart: on-failure
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 10s
      timeout: 5s
      retries: 3

secrets:
  db_password:
    file: ./secrets/db_password.txt
  db_root_password:
    file: ./secrets/db_root_password.txt
  wp_admin_password:
    file: ./secrets/wp_admin_password.txt
  wp_user_password:
    file: ./secrets/wp_user_password.txt

networks:
  inception_network:
    driver: bridge

volumes:
  vol_nginx_wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/jeberle/data'
  vol_mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/jeberle/data'