secrets:
  db_password:
    file: ./secrets/db_password.txt
  db_root_password:
    file: ./secrets/db_root_password.txt
  wp_password:
    file: ./secrets/wp_password.txt

services:
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "443:443"
    networks:
      - inception_network
    restart: always

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    depends_on:
      - mariadb
    networks:
      - inception_network
    volumes:
      - wordpress_data:/var/www/html
    restart: always

  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    networks:
      - inception_network
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: always


volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./requirements/wordpress/data
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./requirements/mariadb/data

networks:
  inception_network:
    driver: bridge