version: '3.8'

secrets:
  db_password:
    file: ./secrets/db_password.txt
  db_root_password:
    file: ./secrets/db_root_password.txt
  wp_password:
    file: ./secrets/wp_password.txt

services:
  nginx:
    build: 
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "443:443"
    networks:
      - inception_network
    restart: always


networks:
  inception_network:
    driver: bridge