<<<<<<< HEAD
secrets:
  db_password:
    file: ./secrets/db_password.txt
  db_root_password:
    file: ./secrets/db_root_password.txt
  wp_password:
    file: ./secrets/wp_password.txt
=======
version: '3'
>>>>>>> 299f4311ae3fd1066c2b3e3b5ccff4e824419bce

services:
  nginx:
    build:
      context: ./requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - ./data/wordpress:/var/www/html
    networks:
      - inception_network
    depends_on:
      - wordpress
    restart: always

  wordpress:
    build:
      context: ./requirements/wordpress
    container_name: wordpress
    volumes:
      - ./data/wordpress:/var/www/html
    networks:
      - inception_network
    depends_on:
      - mariadb
    env_file:
      - .env
    restart: always

<<<<<<< HEAD
  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    depends_on:
      - mariadb
    networks:
      - inception_network
    volumes:
      - wordpress_data:/var/www/html
    restart: always

  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    networks:
      - inception_network
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: always


volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./requirements/wordpress/data
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./requirements/mariadb/data
=======
  mariadb:
    build:
      context: ./requirements/mariadb
    container_name: mariadb
    volumes:
      - ./data/mariadb:/var/lib/mysql
    networks:
      - inception_network
    env_file:
      - .env
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 10s
      timeout: 5s
      retries: 3
>>>>>>> 299f4311ae3fd1066c2b3e3b5ccff4e824419bce

networks:
  inception_network:
    driver: bridge
