services:
  nginx:
    build:
      context: ./requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - ./data/wordpress:/var/www/html
    networks:
      - inception_network
    depends_on:
      - wordpress
    restart: unless-stopped

wordpress:
  build:
    context: ./requirements/wordpress
  container_name: wordpress
  volumes:
    - ./data/wordpress:/var/www/html
  networks:
    - inception_network
  depends_on:
    - mariadb
  environment:
    - DOMAIN_NAME=jeberle.42.fr
    - WP_TITLE=Inception
    - WP_ADMIN_USER=supervisor
    - WP_ADMIN_EMAIL=jeberle@student.42.fr
    - WP_USER=wp_regular_user
    - WP_USER_EMAIL=regular_user@42.fr
    - MYSQL_DATABASE=wordpress
    - MYSQL_USER=wp_user
  secrets:
    - db_password
    - db_root_password
    - wp_admin_password
    - wp_user_password
  restart: unless-stopped

  mariadb:
    build:
      context: ./requirements/mariadb
    container_name: mariadb
    secrets:
      - db_password
      - db_root_password
    environment:
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wp_user
    volumes:
      - ./data/mariadb:/var/lib/mysql
    networks:
      - inception_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 10s
      timeout: 5s
      retries: 3

secrets:
  db_password:
    file: ./secrets/db_password.txt
  db_root_password:
    file: ./secrets/db_root_password.txt
  wp_admin_password:
    file: ./secrets/wp_admin_password.txt
  wp_user_password:
    file: ./secrets/wp_user_password.txt

networks:
  inception_network:
    driver: bridge
